### ISSUE TITLE
Create one PR template

### ISSUE THREAD

**Issue by debdutgoswami** [dscaot/links#1]
Create a template inside `.github/`. If you don't know how to create one then look into this [link](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository)

**Comment by IC1101Virgo** [comment]
Can I work on this?

**Comment by debdutgoswami** [comment]
@IC1101Virgo Sorry hacktober fest hasn't started yet.

**Comment by IC1101Virgo** [comment]
> @IC1101Virgo Sorry hacktober fest hasn't started yet.

Forgive me ! 😃

**Comment by Rupinderjeet2004** [comment]
Hi there, Can I work on this?

**Comment by PriyanshTri** [comment]
@debdutgoswami assign this to me. thanks

**Comment by debdutgoswami** [comment]
@PriyanshTri go-ahead

**Comment by PriyanshTri** [comment]
what things should be included in Template? any specific note?

**Comment by debdutgoswami** [comment]
@PriyanshTri No, feel free to use your own template.

**Comment by PriyanshTri** [comment]
please see this PR #10 and merge it asap..

**Comment by debdutgoswami** [comment]
@PriyanshTri Merged. Thanks for contributing.
