### ISSUE TITLE
Create a BUG report template (ISSUE TEMPLATE)

### ISSUE THREAD

**Issue by debdutgoswami** [dscaot/links#2]
Create a template inside `.github/`. If you don't know how to create one then look into this [link](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository)

This should be a `BUG REPORT` template.

**Comment by ritik-patel05** [comment]
Can I work on this?

**Comment by debdutgoswami** [comment]
@RitikPPatel05 Sorry hacktoberfest hasn't started yet
