### ISSUE TITLE
Improve the current README

### ISSUE THREAD

**Issue by debdutgoswami** [dscaot/links#5]
- Add Screenshot of the hosted page
- Add Tech Stack
- Add Description
- Add tags like PR Ready, etc

**Comment by sambhavjain9138** [comment]
Heyy
I would like to contribute on the issue. Please assign it to me

**Comment by debdutgoswami** [comment]
@sambhavjain9138 Really sorry but these issues are for Academy Of Technology students only.

**Comment by sambhavjain9138** [comment]
Okay got it. Thank for the update @debdutgoswami

**Comment by Triparna-Ganguly** [comment]
@debdutgoswami what more?
